name: Build

on:
  push:
    #tags:
    #- "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Docker Actions
      uses: gexops/actions@main
      id: actions
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_password }}
        semantic_version_enabled: 'true'

    - name: Push Docker
      run: make push

    #- uses: "marvinpinto/action-automatic-releases@latest"
    #  with:
    #    repo_token: "${{ secrets.GITHUB_TOKEN }}"
    #    prerelease: false
